### PR TITLE
Update website for 2017

### PR DESCRIPTION
**Pull request by ottaviohartman**
- Update links
- Add new TAs and remove old ones
- Change CSS to make website more mobile-friendly
- Add headshots
- Remove lectures/ and images/projects

Missing: 
- Headshot for Josh Phillip Lawrence
- Emails for Josh, Jin, and Mohamad

### CODE REVIEW

**Comment by pjcozzi** [comment]
@omh1280 perhaps use the headshot in @loshjawrence's GitHub profile?  @loshjawrence if you want to use something else, please open a pull request.

**Comment by pjcozzi** [comment]
@byumjin @loshjawrence @moneimne please provide your preferred emails for the CIS 565 website for your student advisor roles.

**Comment by pjcozzi** [comment]
@omh1280 thanks for jumping on this!

Could you:
* Create a new banner image of your selection from last year's final projects!!! 😄 
* Remove all the old stuff from the README.md?  Just a banner and link to the website is OK.
* For "All former TAs have helped shape this course", please do not remove any of the previous TAs.

I'll also make some tweaks to the **Description** probably tomorrow.

Thanks again!

**Comment by moneimne** [comment]
moneimne@seas.upenn.edu works for me!

**Comment by byumjin** [comment]
byumjin@seas.upenn.edu

**Comment by ottaviohartman** [comment]
This is ready to be merged, unless there are more changes needed! @CIS565-Fall-2017/tas

**Comment by pjcozzi** [comment]
@omh1280 thanks for taking the lead on this!!!

**Pull request merged**
